#!/bin/sh /etc/rc.common
# Copyright (c) 2011-2015 OpenWrt.org

START=99

start() {
	if [ ! -f "/var/run/your_bot_name.pid" ]; then
		echo "1" > /var/run/your_bot_name.pid
		python3 /usr/lib/telebot/your_bot_name.py >/dev/null 2>&1 &
	fi
	return 0
}

stop() {
	rm -f /var/run/your_bot_name.pid
	kill $(pgrep -f telebot/your_bot_name.py) >/dev/null 2>&1
}

restart(){
	stop
	sleep 1
	start
}

boot() {
	(sleep 5 && start >/dev/null 2>&1) &
	return 0
}
